[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35463",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35463/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35463/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35463/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35463",
    "id": 667943015,
    "node_id": "MDU6SXNzdWU2Njc5NDMwMTU=",
    "number": 35463,
    "title": "Question/bug: How to get rid of \"0 days\" in timedelta64[s]",
    "user": {
      "login": "pllim",
      "id": 2090236,
      "node_id": "MDQ6VXNlcjIwOTAyMzY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2090236?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pllim",
      "html_url": "https://github.com/pllim",
      "followers_url": "https://api.github.com/users/pllim/followers",
      "following_url": "https://api.github.com/users/pllim/following{/other_user}",
      "gists_url": "https://api.github.com/users/pllim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pllim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pllim/subscriptions",
      "organizations_url": "https://api.github.com/users/pllim/orgs",
      "repos_url": "https://api.github.com/users/pllim/repos",
      "events_url": "https://api.github.com/users/pllim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pllim/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T15:40:00Z",
    "updated_at": "2020-07-29T15:40:00Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas. -- I can't tell if this is a feature or a bug.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\n>>> import pandas as pd\r\n>>> import numpy as np\r\n>>> dt = pd.Series(np.array([1, 300], dtype='timedelta64[s]')) \r\n>>> df = pd.DataFrame({'dt': dt})\r\n```\r\n```python\r\n>>> pd.__version__\r\n'1.0.5'\r\n>>> df\r\n        dt\r\n0 00:00:01\r\n1 00:05:00\r\n```\r\n```python\r\n>>> pd.__version__\r\n'1.1.0'\r\n>>> df\r\n               dt\r\n0 0 days 00:00:01\r\n1 0 days 00:05:00\r\n```\r\n\r\n#### Problem description\r\n\r\n\"0 days\" started to appear when DataFrame contains `timedelta64[s]`.\r\n\r\n#### Expected Output\r\n\r\nSee \"Code Sample\" for `pandas` 1.0.5.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\nSee \"Code Sample\" for `pandas` 1.1.0.\r\n\r\n#### Further readings\r\n\r\nastropy/astropy#10608 and astropy/astropy#10609",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35462",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35462/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35462/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35462/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35462",
    "id": 667930415,
    "node_id": "MDU6SXNzdWU2Njc5MzA0MTU=",
    "number": 35462,
    "title": "BUG: dataframe.apply() loops on first row when applied method attempts to modify the row",
    "user": {
      "login": "nicolasrozain",
      "id": 16897168,
      "node_id": "MDQ6VXNlcjE2ODk3MTY4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/16897168?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nicolasrozain",
      "html_url": "https://github.com/nicolasrozain",
      "followers_url": "https://api.github.com/users/nicolasrozain/followers",
      "following_url": "https://api.github.com/users/nicolasrozain/following{/other_user}",
      "gists_url": "https://api.github.com/users/nicolasrozain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nicolasrozain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nicolasrozain/subscriptions",
      "organizations_url": "https://api.github.com/users/nicolasrozain/orgs",
      "repos_url": "https://api.github.com/users/nicolasrozain/repos",
      "events_url": "https://api.github.com/users/nicolasrozain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nicolasrozain/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T15:21:58Z",
    "updated_at": "2020-07-29T15:23:09Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "With pandas 1.1.0 on Python 3.6.8:\r\n\r\n```\r\n>>> import pandas as pd\r\n>>> df = pd.DataFrame({'a': list(range(0,100)), 'b': list(range(100,200))})\r\n>>> def func(row):\r\n...     row.loc['a'] += 1\r\n...     return row\r\n... \r\n>>> df\r\n     a    b\r\n0    0  100\r\n1    1  101\r\n2    2  102\r\n3    3  103\r\n4    4  104\r\n..  ..  ...\r\n95  95  195\r\n96  96  196\r\n97  97  197\r\n98  98  198\r\n99  99  199\r\n[100 rows x 2 columns]\r\n>>> df.apply(func, axis=1)\r\n      a    b\r\n0   100  100\r\n1   100  100\r\n2   100  100\r\n3   100  100\r\n4   100  100\r\n..  ...  ...\r\n95  100  100\r\n96  100  100\r\n97  100  100\r\n98  100  100\r\n99  100  100\r\n[100 rows x 2 columns]\r\n>>> df\r\n      a    b\r\n0   100  100\r\n1     1  101\r\n2     2  102\r\n3     3  103\r\n4     4  104\r\n..  ...  ...\r\n95   95  195\r\n96   96  196\r\n97   97  197\r\n98   98  198\r\n99   99  199\r\n[100 rows x 2 columns]\r\n>>> pd.show_versions()\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : d9fff2792bf16178d4e450fe7384244e50635733\r\npython           : 3.6.8.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.17763\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.None\r\npandas           : 1.1.0\r\nnumpy            : 1.18.2\r\npytz             : 2019.3\r\ndateutil         : 2.8.1\r\npip              : 20.0.2\r\nsetuptools       : 42.0.2\r\nCython           : None\r\npytest           : 5.4.1\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.5.0\r\nhtml5lib         : 1.0.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : 4.9.1\r\nbottleneck       : 1.3.2\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.2.1\r\nnumexpr          : 2.7.1\r\nodfpy            : None\r\nopenpyxl         : 2.5.14\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.3.3\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 1.2.0\r\nxlwt             : 1.3.0\r\nnumba            : None\r\n```\r\n\r\nWith pandas 1.0.5:\r\n```\r\n>>> import pandas as pd\r\n>>> df = pd.DataFrame({'a': list(range(0,100)), 'b': list(range(100,200))})\r\n>>> def func(row):\r\n...     row.loc['a'] += 1\r\n...     return row\r\n... \r\n>>> df\r\n     a    b\r\n0    0  100\r\n1    1  101\r\n2    2  102\r\n3    3  103\r\n4    4  104\r\n..  ..  ...\r\n95  95  195\r\n96  96  196\r\n97  97  197\r\n98  98  198\r\n99  99  199\r\n[100 rows x 2 columns]\r\n>>> df.apply(func, axis=1)\r\n      a    b\r\n0     1  100\r\n1     2  101\r\n2     3  102\r\n3     4  103\r\n4     5  104\r\n..  ...  ...\r\n95   96  195\r\n96   97  196\r\n97   98  197\r\n98   99  198\r\n99  100  199\r\n[100 rows x 2 columns]\r\n>>> df\r\n      a    b\r\n0     1  100\r\n1     2  101\r\n2     3  102\r\n3     4  103\r\n4     5  104\r\n..  ...  ...\r\n95   96  195\r\n96   97  196\r\n97   98  197\r\n98   99  198\r\n99  100  199\r\n[100 rows x 2 columns]\r\n>>> pd.show_versions()\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.6.8.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.None\r\npandas           : 1.0.5\r\nnumpy            : 1.18.2\r\npytz             : 2019.3\r\ndateutil         : 2.8.1\r\npip              : 20.0.2\r\nsetuptools       : 42.0.2\r\nCython           : None\r\npytest           : 5.4.1\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.5.0\r\nhtml5lib         : 1.0.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : 4.9.1\r\nbottleneck       : 1.3.2\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : 4.5.0\r\nmatplotlib       : 3.2.1\r\nnumexpr          : 2.7.1\r\nodfpy            : None\r\nopenpyxl         : 2.5.14\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : 5.4.1\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.3.3\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 1.2.0\r\nxlwt             : 1.3.0\r\nxlsxwriter       : None\r\nnumba            : None\r\n```\r\n\r\nI expected the behavior of 1.0.5 in 1.1.0, did I misunderstood the apply method?\r\nThank you for your help.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35461",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35461/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35461/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35461/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35461",
    "id": 667930090,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4NTEwNDgw",
    "number": 35461,
    "title": "CI: activate azure pipelines on 1.1.x - DO NOT MERGE",
    "user": {
      "login": "simonjayhawkins",
      "id": 13159005,
      "node_id": "MDQ6VXNlcjEzMTU5MDA1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13159005?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/simonjayhawkins",
      "html_url": "https://github.com/simonjayhawkins",
      "followers_url": "https://api.github.com/users/simonjayhawkins/followers",
      "following_url": "https://api.github.com/users/simonjayhawkins/following{/other_user}",
      "gists_url": "https://api.github.com/users/simonjayhawkins/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/simonjayhawkins/subscriptions",
      "organizations_url": "https://api.github.com/users/simonjayhawkins/orgs",
      "repos_url": "https://api.github.com/users/simonjayhawkins/repos",
      "events_url": "https://api.github.com/users/simonjayhawkins/events{/privacy}",
      "received_events_url": "https://api.github.com/users/simonjayhawkins/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 48070600,
        "node_id": "MDU6TGFiZWw0ODA3MDYwMA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/CI",
        "name": "CI",
        "color": "a2bca7",
        "default": false,
        "description": "Related to Continuous Integration"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T15:21:32Z",
    "updated_at": "2020-07-29T15:21:32Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35461",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35461",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35461.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35461.patch"
    },
    "body": "Azure pipelines worked for 1.0.x since #32706 which specified which branches to run on was not backported\r\n\r\nIf works. will open PR against master instead. and backport.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35460",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35460/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35460/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35460/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35460",
    "id": 667909950,
    "node_id": "MDU6SXNzdWU2Njc5MDk5NTA=",
    "number": 35460,
    "title": "BUG: AssertionError: Number of Block dimensions (1) must equal number of axes (2) when typing a column",
    "user": {
      "login": "frd-glovo",
      "id": 56838676,
      "node_id": "MDQ6VXNlcjU2ODM4Njc2",
      "avatar_url": "https://avatars1.githubusercontent.com/u/56838676?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frd-glovo",
      "html_url": "https://github.com/frd-glovo",
      "followers_url": "https://api.github.com/users/frd-glovo/followers",
      "following_url": "https://api.github.com/users/frd-glovo/following{/other_user}",
      "gists_url": "https://api.github.com/users/frd-glovo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frd-glovo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frd-glovo/subscriptions",
      "organizations_url": "https://api.github.com/users/frd-glovo/orgs",
      "repos_url": "https://api.github.com/users/frd-glovo/repos",
      "events_url": "https://api.github.com/users/frd-glovo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frd-glovo/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2020-07-29T14:54:57Z",
    "updated_at": "2020-07-29T15:10:07Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\ndf = pd.DataFrame(\r\n            {\"e1_timestamp\": [],\r\n                \"e2_timestamp\": []\r\n            }\r\n        )\r\n\r\n# The problematic code. Remove this and there are no exceptions. \r\n\r\nfor timefield in [\r\n        \"e1_timestamp\",\r\n        \"e2_timestamp\",\r\n    ]:\r\n        df[timefield] = pd.to_datetime(df[timefield], utc=True)\r\n#\r\n\r\ndf = df.append({\r\n                    \"orderId\": 1,\r\n                    \"e1_timestamp\": pd.to_datetime(pd.NaT, utc=True),\r\n                    \"e2_timestamp\": pd.to_datetime(pd.NaT, utc=True),\r\n                },ignore_index=True,)\r\ndf\r\n```\r\n\r\n#### Problem description\r\n\r\nWhy initializing an empty dataframe, defining its type as shown in the example and then appending a value, there is an ```AssertionError: Number of Block dimensions (1) must equal number of axes (2)``` exception.\r\n\r\nIf we remove the for loop, it does work: \r\n```\r\ndf = pd.DataFrame(\r\n            {\"e1_timestamp\": [],\r\n                \"e2_timestamp\": []\r\n            }\r\n        )\r\n\r\ndf = df.append({\r\n                    \r\n                    \"e1_timestamp\": pd.to_datetime(pd.NaT, utc=True),\r\n                    \"e2_timestamp\": pd.to_datetime(pd.NaT, utc=True),\r\n                },ignore_index=True,)\r\n\r\n\r\ndf\r\n```\r\n\r\nWe see that we could do ```df = df.astype({\"e1_timestamp\": 'datetime64[ns]', \"e1_timestamp\":  'datetime64[ns]'})``` instead of that for loop, but there seems to be a bug in this new version. With pandas==1.0.5 the for loop does not raise an exception.\r\n\r\n#### Expected Output\r\n\r\nThere should be no assertion error\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : d9fff2792bf16178d4e450fe7384244e50635733\r\npython           : 3.7.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 4.9.184-linuxkit\r\nVersion          : #1 SMP Tue Jul 2 22:58:16 UTC 2019\r\nmachine          : x86_64\r\nprocessor        : \r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.16.0\r\npytz             : 2019.1\r\ndateutil         : 2.8.1\r\npip              : 19.3.1\r\nsetuptools       : 41.4.0\r\nCython           : None\r\npytest           : 4.1.1\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : 0.9.3\r\npsycopg2         : 2.8.2 (dt dec pq3 ext lo64)\r\njinja2           : 2.10.1\r\nIPython          : 7.11.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.1.1\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.2.0\r\nsqlalchemy       : 1.2.16\r\ntables           : None\r\ntabulate         : 0.8.3\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35459",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35459/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35459/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35459/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35459",
    "id": 667909684,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4NDkzNDE5",
    "number": 35459,
    "title": "CI: activate github actions on 1.1.x (PR only) - DO NOT MERGE",
    "user": {
      "login": "simonjayhawkins",
      "id": 13159005,
      "node_id": "MDQ6VXNlcjEzMTU5MDA1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13159005?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/simonjayhawkins",
      "html_url": "https://github.com/simonjayhawkins",
      "followers_url": "https://api.github.com/users/simonjayhawkins/followers",
      "following_url": "https://api.github.com/users/simonjayhawkins/following{/other_user}",
      "gists_url": "https://api.github.com/users/simonjayhawkins/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/simonjayhawkins/subscriptions",
      "organizations_url": "https://api.github.com/users/simonjayhawkins/orgs",
      "repos_url": "https://api.github.com/users/simonjayhawkins/repos",
      "events_url": "https://api.github.com/users/simonjayhawkins/events{/privacy}",
      "received_events_url": "https://api.github.com/users/simonjayhawkins/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 48070600,
        "node_id": "MDU6TGFiZWw0ODA3MDYwMA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/CI",
        "name": "CI",
        "color": "a2bca7",
        "default": false,
        "description": "Related to Continuous Integration"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T14:54:36Z",
    "updated_at": "2020-07-29T15:00:46Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35459",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35459",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35459.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35459.patch"
    },
    "body": "IIUC without changes to other scripts, activating GitHub actions for merge would push the docs. so this is only for PRs\r\n\r\nIf works. will open PR against master instead. and backport.\r\n\r\nxref https://github.com/pandas-dev/pandas/pull/34800#issuecomment-644669496",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35456",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35456/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35456/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35456/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35456",
    "id": 667832696,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4NDI4OTg4",
    "number": 35456,
    "title": "Add note about limited propagation of attrs",
    "user": {
      "login": "RobertRosca",
      "id": 32569096,
      "node_id": "MDQ6VXNlcjMyNTY5MDk2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/32569096?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RobertRosca",
      "html_url": "https://github.com/RobertRosca",
      "followers_url": "https://api.github.com/users/RobertRosca/followers",
      "following_url": "https://api.github.com/users/RobertRosca/following{/other_user}",
      "gists_url": "https://api.github.com/users/RobertRosca/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RobertRosca/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RobertRosca/subscriptions",
      "organizations_url": "https://api.github.com/users/RobertRosca/orgs",
      "repos_url": "https://api.github.com/users/RobertRosca/repos",
      "events_url": "https://api.github.com/users/RobertRosca/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RobertRosca/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T13:09:59Z",
    "updated_at": "2020-07-29T13:09:59Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35456",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35456",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35456.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35456.patch"
    },
    "body": "Explicitly mention that `attrs` are not retained once a series is placed into a dataframe, related to issue #35425",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35455",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35455/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35455/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35455/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35455",
    "id": 667809198,
    "node_id": "MDU6SXNzdWU2Njc4MDkxOTg=",
    "number": 35455,
    "title": "REGR: DataFrame.to_numpy(dtype=str) raises RuntimeError in pandas 1.1.0",
    "user": {
      "login": "aciba90",
      "id": 22963691,
      "node_id": "MDQ6VXNlcjIyOTYzNjkx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/22963691?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aciba90",
      "html_url": "https://github.com/aciba90",
      "followers_url": "https://api.github.com/users/aciba90/followers",
      "following_url": "https://api.github.com/users/aciba90/following{/other_user}",
      "gists_url": "https://api.github.com/users/aciba90/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aciba90/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aciba90/subscriptions",
      "organizations_url": "https://api.github.com/users/aciba90/orgs",
      "repos_url": "https://api.github.com/users/aciba90/repos",
      "events_url": "https://api.github.com/users/aciba90/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aciba90/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 31404521,
        "node_id": "MDU6TGFiZWwzMTQwNDUyMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Dtypes",
        "name": "Dtypes",
        "color": "e102d8",
        "default": false,
        "description": null
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/75",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels",
      "id": 5640672,
      "node_id": "MDk6TWlsZXN0b25lNTY0MDY3Mg==",
      "number": 75,
      "title": "1.1.1",
      "description": "on-merge: backport to 1.1.x",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 14,
      "closed_issues": 4,
      "state": "open",
      "created_at": "2020-07-10T13:54:44Z",
      "updated_at": "2020-07-29T15:59:29Z",
      "due_on": "2020-08-15T07:00:00Z",
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2020-07-29T12:33:12Z",
    "updated_at": "2020-07-29T13:41:27Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x ] I have checked that this issue has not already been reported.\r\n\r\n- [x ] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\ndf = pd.DataFrame(data=[[pd.Timestamp('2011-07-03 00:00:00'), 6628480.0]])\r\nprint(df.to_numpy(dtype=str))\r\n```\r\n\r\n#### Problem description\r\n\r\nI try to convert the DataFrame to a Numpy array with dtype equal to str and I got the next error.\r\n\r\n```python-traceback\r\nTraceback (most recent call last):\r\n  File \"/main.py\", line 4, in <module>\r\n    df.to_numpy(dtype=str)\r\n  File \"/venv/lib/python3.7/site-packages/pandas/core/frame.py\", line 1371, in to_numpy\r\n    transpose=self._AXIS_REVERSED, dtype=dtype, copy=copy, na_value=na_value\r\n  File \"/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py\", line 826, in as_array\r\n    arr = self._interleave(dtype=dtype, na_value=na_value)\r\n  File \"/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py\", line 864, in _interleave\r\n    result[rl.indexer] = arr\r\nRuntimeError: The string provided for NumPy ISO datetime formatting was too short, with length 1\r\n```\r\n\r\n#### Expected Output\r\n```python\r\n[['2011-07-03 00:00:00' '6628480.0']]\r\n```\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : d9fff2792bf16178d4e450fe7384244e50635733\r\npython           : 3.7.6.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 4.19.104-microsoft-standard\r\nVersion          : #1 SMP Wed Feb 19 06:37:35 UTC 2020\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 19.2.3\r\nsetuptools       : 41.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35451",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35451/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35451/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35451/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35451",
    "id": 667761552,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MzY5MDgw",
    "number": 35451,
    "title": "WEB: Fixing whatsnew link in the home page (version was hardcoded)",
    "user": {
      "login": "datapythonista",
      "id": 10058240,
      "node_id": "MDQ6VXNlcjEwMDU4MjQw",
      "avatar_url": "https://avatars2.githubusercontent.com/u/10058240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/datapythonista",
      "html_url": "https://github.com/datapythonista",
      "followers_url": "https://api.github.com/users/datapythonista/followers",
      "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
      "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
      "organizations_url": "https://api.github.com/users/datapythonista/orgs",
      "repos_url": "https://api.github.com/users/datapythonista/repos",
      "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
      "received_events_url": "https://api.github.com/users/datapythonista/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1508144531,
        "node_id": "MDU6TGFiZWwxNTA4MTQ0NTMx",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Web",
        "name": "Web",
        "color": "23ef97",
        "default": false,
        "description": "pandas website"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2020-07-29T11:14:06Z",
    "updated_at": "2020-07-29T11:31:17Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35451",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35451",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35451.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35451.patch"
    },
    "body": "",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35450",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35450/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35450/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35450/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35450",
    "id": 667753795,
    "node_id": "MDU6SXNzdWU2Njc3NTM3OTU=",
    "number": 35450,
    "title": "BUG: dataframe.any() method behaves differently for empty rows and columns",
    "user": {
      "login": "simplyrucha",
      "id": 60076143,
      "node_id": "MDQ6VXNlcjYwMDc2MTQz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/60076143?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/simplyrucha",
      "html_url": "https://github.com/simplyrucha",
      "followers_url": "https://api.github.com/users/simplyrucha/followers",
      "following_url": "https://api.github.com/users/simplyrucha/following{/other_user}",
      "gists_url": "https://api.github.com/users/simplyrucha/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/simplyrucha/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/simplyrucha/subscriptions",
      "organizations_url": "https://api.github.com/users/simplyrucha/orgs",
      "repos_url": "https://api.github.com/users/simplyrucha/repos",
      "events_url": "https://api.github.com/users/simplyrucha/events{/privacy}",
      "received_events_url": "https://api.github.com/users/simplyrucha/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T11:01:47Z",
    "updated_at": "2020-07-29T11:01:47Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [ ] I have checked that this issue has not already been reported. \r\n\r\n- [ ] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\ndf1 = pd.DataFrame(data = {\"A\" : [np.nan, 1], \"B\": [np.nan, 2], \"C\": [np.nan, np.nan]})\r\n\r\ndf2 = pd.DataFrame(data = [[np.nan, 1],\r\n                          [np.nan, 2],\r\n                          [np.nan, np.nan]],\r\n                   columns = [\"A\", \"B\"])\r\n\r\n# dataframe created with mixed values of bool and numeric with shape - 4,4\r\ndf3 = pd.DataFrame(data = [[1, np.nan, np.nan, True],\r\n                           [np.nan, 2, np.nan, True],\r\n                           [np.nan, np.nan, np.nan, False],\r\n                           [np.nan, np.nan, np.nan, np.nan]],\r\n                   columns = [\"col1\", \"col2\", \"col3\", \"col4\"])\r\n```\r\n\r\n#### Problem description\r\n\r\nThe [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.any.html) for any() method states that for empty row/column, **np.nan is treated as True**. So if the parameter \"skipna = False\", then the empty row should result in True for either, axis = 0/ index or 1/columns. \r\n\r\nThe dataframe.any(skipna = False, axis = {1 or 0}) method works as documented for df1 and df2. However, it behaves differently for df3. \r\n\r\n(Similar output is obtained for df1 as well hence not included here) The obtained output for df2 is like this:\r\n\r\n```\r\n# df2.any(axis = 1, skipna = False) # df2.any(axis = \"columns\", skipna = False)\r\n0    True\r\n1    True\r\n2    True\r\ndtype: bool \r\n\r\n# df2.any(axis = 0, skipna = False) # df2.any(axis = \"index\", skipna = False)\r\nA    True\r\nB    True\r\ndtype: bool\r\n```\r\n\r\nThe obtained output for df3 is like this:\r\n\r\n```\r\n# df3.any(axis = 1, skipna = False) # df3.any(axis = \"columns\", skipna = False)\r\n0      1\r\n1    NaN\r\n2    NaN\r\n3    NaN\r\ndtype: object \r\n\r\n# df3.any(axis = 0, skipna = False) # df3.any(axis = \"index\", skipna = False)\r\ncol1       1\r\ncol2     NaN\r\ncol3     NaN\r\ncol4    True\r\ndtype: object \r\n\r\n```\r\n\r\n#### Expected Output\r\n\r\n```\r\n# The expected output for df3 should be, similar to df2's output, and like this: \r\n\r\n# df3.any(axis = 1, skipna = False) # df3.any(axis = \"columns\", skipna = False)\r\n0    True\r\n1    True\r\n2    True\r\n3    True\r\ndtype: object \r\n    \r\n# df3.any(axis = 0, skipna = False) # df3.any(axis = \"index\", skipna = False)\r\nCol1    True\r\nCol2    True\r\nCol3    True\r\nCol4    True\r\ndtype: object\r\n\r\n```\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\n[INSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.7.4.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.None\r\n\r\npandas           : 1.0.4\r\nnumpy            : 1.16.5\r\npytz             : 2019.3\r\ndateutil         : 2.8.0\r\npip              : 19.2.3\r\nsetuptools       : 41.4.0\r\nCython           : 0.29.13\r\npytest           : 5.2.1\r\nhypothesis       : None\r\nsphinx           : 2.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 1.2.1\r\nlxml.etree       : 4.4.1\r\nhtml5lib         : 1.0.1\r\npymysql          : None\r\npsycopg2         : 2.8.4 (dt dec pq3 ext lo64)\r\njinja2           : 2.11.2\r\nIPython          : 7.8.0\r\npandas_datareader: None\r\nbs4              : 4.8.0\r\nbottleneck       : 1.2.1\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : 4.4.1\r\nmatplotlib       : 3.2.1\r\nnumexpr          : 2.7.0\r\nodfpy            : None\r\nopenpyxl         : 3.0.0\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : 5.2.1\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.4.1\r\nsqlalchemy       : 1.3.9\r\ntables           : 3.5.2\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 1.2.0\r\nxlwt             : 1.3.0\r\nxlsxwriter       : 1.2.1\r\nnumba            : 0.45.1]\r\n\r\n</details>\r\n\r\nI am not sure where exactly I am going wrong with df3. I also thought of appending this issue with the open issue related to \"bool_only\" parameter [here](https://github.com/pandas-dev/pandas/issues/32432). But then before reporting this confusion/error I tried the dataframe.any()method on df1 and df2, without using parameter \"bool_only\" and it gives the correct result. However, it again behaves very differently for df3. \r\n\r\nSince I might have already crossed, the threshold of a minimal bug report, my experiments with the bool_only parameter are in the attached \"Any_Experiments.ipynb\" file. \r\n[Any_Experiments.zip](https://github.com/pandas-dev/pandas/files/4994395/Any_Experiments.zip)\r\n\r\nThis is my first issue/ bug/ query to Pandas. Apologies for typos and/or any violations of reporting guidelines. \r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35449",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35449/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35449/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35449/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35449",
    "id": 667700671,
    "node_id": "MDU6SXNzdWU2Njc3MDA2NzE=",
    "number": 35449,
    "title": "BUG: unique() casts its types' elements from `pd.Timestamp` to `numpy.datetime64`",
    "user": {
      "login": "SebastianoX",
      "id": 67270366,
      "node_id": "MDQ6VXNlcjY3MjcwMzY2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/67270366?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/SebastianoX",
      "html_url": "https://github.com/SebastianoX",
      "followers_url": "https://api.github.com/users/SebastianoX/followers",
      "following_url": "https://api.github.com/users/SebastianoX/following{/other_user}",
      "gists_url": "https://api.github.com/users/SebastianoX/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/SebastianoX/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SebastianoX/subscriptions",
      "organizations_url": "https://api.github.com/users/SebastianoX/orgs",
      "repos_url": "https://api.github.com/users/SebastianoX/repos",
      "events_url": "https://api.github.com/users/SebastianoX/events{/privacy}",
      "received_events_url": "https://api.github.com/users/SebastianoX/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T09:39:11Z",
    "updated_at": "2020-07-29T09:47:36Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample\r\n\r\n```python\r\nimport pandas as pd \r\n \r\n \r\ndf = pd.DataFrame({\"date\": [\"2019-02-10\", \"2019-02-11\"]}) \r\ndf[\"date\"] = pd.to_datetime(df[\"date\"]) \r\n \r\nprint(\"Date Types in column date:\") \r\nfor day in df[\"date\"]: \r\n    print(type(day))  # pandas._libs.tslibs.timestamps.Timestamp \r\n \r\nprint(\"Unique date Types in column date:\") \r\nfor day in df[\"date\"].unique():  \r\n    print(type(day))  # np.datetime64 \r\n\r\n```\r\n\r\nThe code above results in:\r\n\r\n```\r\nDate Types in column date:\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n\r\nUnique date Types in column date:\r\n<class 'numpy.datetime64'>\r\n<class 'numpy.datetime64'>\r\n```\r\n\r\n#### Problem description\r\n\r\nThe class method `unique()` should not change the type of the elements in the original column.\r\n\r\n#### Expected Output\r\n\r\n```\r\nDate Types in column date:\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n\r\nUnique date Types in column date:\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n<class 'pandas._libs.tslibs.timestamps.Timestamp'>\r\n```\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.7.7.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.5.0\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.0.5\r\nnumpy            : 1.19.0\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 47.3.1\r\nCython           : None\r\npytest           : 5.4.1\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.2\r\nIPython          : 7.16.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : 3.2.2\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : 5.4.1\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.5.2\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>\r\n\r\n\r\n#### Note\r\n\r\nIssue related to #35448, where in the thread I have been asked to re-create it with a clearer OP.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35447",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35447/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35447/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35447/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35447",
    "id": 667655555,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MjgwOTc1",
    "number": 35447,
    "title": "Updated chunksize docstring for DataFrame.to_csv()",
    "user": {
      "login": "Mandera",
      "id": 5393746,
      "node_id": "MDQ6VXNlcjUzOTM3NDY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5393746?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Mandera",
      "html_url": "https://github.com/Mandera",
      "followers_url": "https://api.github.com/users/Mandera/followers",
      "following_url": "https://api.github.com/users/Mandera/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mandera/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mandera/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mandera/subscriptions",
      "organizations_url": "https://api.github.com/users/Mandera/orgs",
      "repos_url": "https://api.github.com/users/Mandera/repos",
      "events_url": "https://api.github.com/users/Mandera/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mandera/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T08:31:46Z",
    "updated_at": "2020-07-29T08:31:46Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35447",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35447",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35447.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35447.patch"
    },
    "body": "Added the documentation for what happens if chunksize is left as None.\r\nIs there a good way to make this DRY somehow?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35446",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35446/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35446/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35446/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35446",
    "id": 667576892,
    "node_id": "MDU6SXNzdWU2Njc1NzY4OTI=",
    "number": 35446,
    "title": "BUG: pd.testing.assert_frame_equal(..., check_exact=True) raises assertion error if any columns are not numeric",
    "user": {
      "login": "ivirshup",
      "id": 8238804,
      "node_id": "MDQ6VXNlcjgyMzg4MDQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8238804?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivirshup",
      "html_url": "https://github.com/ivirshup",
      "followers_url": "https://api.github.com/users/ivirshup/followers",
      "following_url": "https://api.github.com/users/ivirshup/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivirshup/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivirshup/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivirshup/subscriptions",
      "organizations_url": "https://api.github.com/users/ivirshup/orgs",
      "repos_url": "https://api.github.com/users/ivirshup/repos",
      "events_url": "https://api.github.com/users/ivirshup/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivirshup/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      },
      {
        "id": 127685,
        "node_id": "MDU6TGFiZWwxMjc2ODU=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Testing",
        "name": "Testing",
        "color": "C4A000",
        "default": false,
        "description": "Custom testing functions or related to the test suite"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/75",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels",
      "id": 5640672,
      "node_id": "MDk6TWlsZXN0b25lNTY0MDY3Mg==",
      "number": 75,
      "title": "1.1.1",
      "description": "on-merge: backport to 1.1.x",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 14,
      "closed_issues": 4,
      "state": "open",
      "created_at": "2020-07-10T13:54:44Z",
      "updated_at": "2020-07-29T15:59:29Z",
      "due_on": "2020-08-15T07:00:00Z",
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2020-07-29T06:08:13Z",
    "updated_at": "2020-07-29T11:18:47Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\na = pd.DataFrame({\"a\": list(\"bc\"), \"b\": [1, 2]})\r\npd.testing.assert_frame_equal(a, a.copy(), check_exact=True)\r\n```\r\n\r\n```pytb\r\n   ...: a = pd.DataFrame({\"a\": list(\"bc\"), \"b\": [1, 2]}) \r\n   ...: pd.testing.assert_frame_equal(a, a.copy(), check_exact=True)                                                               \r\n---------------------------------------------------------------------------\r\nAssertionError                            Traceback (most recent call last)\r\n<ipython-input-2-bac78c400991> in <module>\r\n      1 import pandas as pd\r\n      2 a = pd.DataFrame({\"a\": list(\"bc\"), \"b\": [1, 2]})\r\n----> 3 pd.testing.assert_frame_equal(a, a.copy(), check_exact=True)\r\n\r\n    [... skipping hidden 2 frame]\r\n\r\nAssertionError: check_exact may only be used with numeric Series\r\n```\r\n\r\n#### Problem description\r\n\r\nPreviously, the example above would not have thrown an error. It makes it a less useful function if I have to start subdividing dataframes by types just to check that they are equal. Presumably check_exact should either have no effect if called on a non-numeric `Series` or `assert_frame_equal` should not pass `check_exact=True` if the series to be compared isn't numeric.\r\n\r\nIt looks like this was introduced recently, in https://github.com/pandas-dev/pandas/commit/08c65973643b73e877133d1a7391de7092f4b267\r\n\r\n#### Expected Output\r\n\r\nI expected it to work like it did previously, and not throw an error. [Here's an example of test failures this is causing](https://travis-ci.org/github/theislab/anndata/jobs/712782637).\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : d9fff2792bf16178d4e450fe7384244e50635733\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.5.0\r\nVersion          : Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.0\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0\r\nCython           : None\r\npytest           : 5.4.3\r\nhypothesis       : None\r\nsphinx           : 3.1.2\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.2\r\nIPython          : 7.16.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : 0.7.4\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.3.0\r\nnumexpr          : 2.7.1\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 0.17.1\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.5.1\r\nsqlalchemy       : 1.3.18\r\ntables           : 3.6.1\r\ntabulate         : None\r\nxarray           : 0.16.0\r\nxlrd             : 1.2.0\r\nxlwt             : None\r\nnumba            : 0.50.1\r\n```\r\n\r\n\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35445",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35445/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35445/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35445/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35445",
    "id": 667543537,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MTg5MDYy",
    "number": 35445,
    "title": "WIP: ENH: Add numba engine to groupby apply",
    "user": {
      "login": "mroeschke",
      "id": 10647082,
      "node_id": "MDQ6VXNlcjEwNjQ3MDgy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/10647082?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mroeschke",
      "html_url": "https://github.com/mroeschke",
      "followers_url": "https://api.github.com/users/mroeschke/followers",
      "following_url": "https://api.github.com/users/mroeschke/following{/other_user}",
      "gists_url": "https://api.github.com/users/mroeschke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mroeschke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mroeschke/subscriptions",
      "organizations_url": "https://api.github.com/users/mroeschke/orgs",
      "repos_url": "https://api.github.com/users/mroeschke/repos",
      "events_url": "https://api.github.com/users/mroeschke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mroeschke/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2020-07-29T04:42:05Z",
    "updated_at": "2020-07-29T04:42:09Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35445",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35445",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35445.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35445.patch"
    },
    "body": "- [x] closes #31845\r\n- [ ] tests added / passed\r\n- [ ] passes `black pandas`\r\n- [ ] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n\r\nSome notes:\r\n\r\n- The passed function must be a reduction op\r\n- The numba engine will drop the grouping column by default\r\n\r\nPreliminary default timing:\r\n\r\n```\r\n(pandas-dev) matthewroeschke:pandas-mroeschke matthewroeschke$ ipython\r\nPython 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09)\r\nType 'copyright', 'credits' or 'license' for more information\r\nIPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.\r\n\r\nIn [1]: df_g = pd.DataFrame({'a': range(10**4), 'b': range(10**4), 'c': range(10**4)})\r\n\r\nIn [2]: def f(x):\r\n   ...:     return np.sum(x) + 1\r\n   ...:\r\n\r\nIn [3]: df_g.groupby('a').apply(f)\r\nOut[3]:\r\n          a      b      c\r\na\r\n0         1      1      1\r\n1         2      2      2\r\n2         3      3      3\r\n3         4      4      4\r\n4         5      5      5\r\n...     ...    ...    ...\r\n9995   9996   9996   9996\r\n9996   9997   9997   9997\r\n9997   9998   9998   9998\r\n9998   9999   9999   9999\r\n9999  10000  10000  10000\r\n\r\n[10000 rows x 3 columns]\r\n\r\nIn [4]: %timeit df_g.groupby('a').apply(f)\r\n3.07 s ± 57.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\r\n\r\nIn [5]: df_g.groupby('a').apply(f, engine='numba', engine_kwargs={'parallel': True})\r\nOut[5]:\r\n            0        1\r\n0         1.0      1.0\r\n1         2.0      2.0\r\n2         3.0      3.0\r\n3         4.0      4.0\r\n4         5.0      5.0\r\n...       ...      ...\r\n9995   9996.0   9996.0\r\n9996   9997.0   9997.0\r\n9997   9998.0   9998.0\r\n9998   9999.0   9999.0\r\n9999  10000.0  10000.0\r\n\r\n[10000 rows x 2 columns]\r\n\r\nIn [6]: %timeit df_g.groupby('a').apply(f, engine='numba', engine_kwargs={'parallel': True})\r\n\r\n510 ms ± 3.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)\r\n```",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35444",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35444/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35444/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35444/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35444",
    "id": 667468615,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MTMwMDQw",
    "number": 35444,
    "title": "BUG: Attributes are lost when subsetting columns in groupby",
    "user": {
      "login": "rhshadrach",
      "id": 45562402,
      "node_id": "MDQ6VXNlcjQ1NTYyNDAy",
      "avatar_url": "https://avatars1.githubusercontent.com/u/45562402?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rhshadrach",
      "html_url": "https://github.com/rhshadrach",
      "followers_url": "https://api.github.com/users/rhshadrach/followers",
      "following_url": "https://api.github.com/users/rhshadrach/following{/other_user}",
      "gists_url": "https://api.github.com/users/rhshadrach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rhshadrach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rhshadrach/subscriptions",
      "organizations_url": "https://api.github.com/users/rhshadrach/orgs",
      "repos_url": "https://api.github.com/users/rhshadrach/repos",
      "events_url": "https://api.github.com/users/rhshadrach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rhshadrach/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 233160,
        "node_id": "MDU6TGFiZWwyMzMxNjA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Groupby",
        "name": "Groupby",
        "color": "729FCF",
        "default": false,
        "description": null
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T00:46:49Z",
    "updated_at": "2020-07-29T02:11:13Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35444",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35444",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35444.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35444.patch"
    },
    "body": "- [x] closes #9959\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n\r\nAvoiding the behavior of Series here, e.g. `df.groupby('a')['b']` as I think that will involve some API changes. Will follow up: ref #35443",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35443",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35443/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35443/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35443/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35443",
    "id": 667468514,
    "node_id": "MDU6SXNzdWU2Njc0Njg1MTQ=",
    "number": 35443,
    "title": "BUG: Attributes of DataFrameGroupBy when subset to a series ",
    "user": {
      "login": "rhshadrach",
      "id": 45562402,
      "node_id": "MDQ6VXNlcjQ1NTYyNDAy",
      "avatar_url": "https://avatars1.githubusercontent.com/u/45562402?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rhshadrach",
      "html_url": "https://github.com/rhshadrach",
      "followers_url": "https://api.github.com/users/rhshadrach/followers",
      "following_url": "https://api.github.com/users/rhshadrach/following{/other_user}",
      "gists_url": "https://api.github.com/users/rhshadrach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rhshadrach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rhshadrach/subscriptions",
      "organizations_url": "https://api.github.com/users/rhshadrach/orgs",
      "repos_url": "https://api.github.com/users/rhshadrach/repos",
      "events_url": "https://api.github.com/users/rhshadrach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rhshadrach/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1741841389,
        "node_id": "MDU6TGFiZWwxNzQxODQxMzg5",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency",
        "name": "API - Consistency",
        "color": "b60205",
        "default": false,
        "description": "Internal Consistency of API/Behavior"
      },
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 233160,
        "node_id": "MDU6TGFiZWwyMzMxNjA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Groupby",
        "name": "Groupby",
        "color": "729FCF",
        "default": false,
        "description": null
      },
      {
        "id": 219960758,
        "node_id": "MDU6TGFiZWwyMTk5NjA3NTg=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion",
        "name": "Needs Discussion",
        "color": "207de5",
        "default": false,
        "description": null
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-29T00:46:28Z",
    "updated_at": "2020-07-29T00:49:09Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "xref #9959 \r\n\r\nWhen subsetting the columns of a dataframe after a groupby to a series:\r\n\r\n    df = pd.DataFrame({'a': [1], 'b': [2], 'c': [3]}).set_index('a')\r\n    g = df.groupby('a')['b']\r\n\r\nthe following public-facing groupby arguments are not passed on to the resulting `SeriesGroupBy`: `axis`, `level`, `as_index`, `sort`, `squeeze` (deprecated), `group_keys`, `dropna`.\r\n\r\nI think the following two examples should probably behave the same:\r\n\r\n    g = df.groupby('a', as_index=False)['b']\r\n    g2 = df['b'].groupby('a', as_index=False)\r\n\r\nbut the first produces\r\n````\r\n   b\r\n0  2\r\n````\r\n\r\nAnd the 2nd deliberately raises `TypeError: as_index=False only valid with DataFrame`.\r\n\r\nNote that the arguments `axis` and `as_index` are only meant for DataFrames, and as such, I think a line such as\r\n\r\n    g = df.groupby('a', as_index=False)['b']\r\n\r\nshould raise.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35441",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35441/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35441/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35441/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35441",
    "id": 667435081,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MTAyMTMw",
    "number": 35441,
    "title": "BUG: GroupBy.apply() throws erroneous ValueError with duplicate axes",
    "user": {
      "login": "smithto1",
      "id": 3813175,
      "node_id": "MDQ6VXNlcjM4MTMxNzU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3813175?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smithto1",
      "html_url": "https://github.com/smithto1",
      "followers_url": "https://api.github.com/users/smithto1/followers",
      "following_url": "https://api.github.com/users/smithto1/following{/other_user}",
      "gists_url": "https://api.github.com/users/smithto1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smithto1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smithto1/subscriptions",
      "organizations_url": "https://api.github.com/users/smithto1/orgs",
      "repos_url": "https://api.github.com/users/smithto1/repos",
      "events_url": "https://api.github.com/users/smithto1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smithto1/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-28T23:02:37Z",
    "updated_at": "2020-07-29T14:14:37Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35441",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35441",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35441.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35441.patch"
    },
    "body": "- [x] closes #16646 \r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [x] whatsnew entry\r\n\r\n*Behavioural Change*\r\n`GroupBy.apply` would sometimes throw an erroneous `ValueError: cannot reindex from duplicate axis` because when it checked if the output was mutated from its original shape it would only check the index, when sometimes it should check the columns. \r\n\r\n*Tests*\r\nOne new test added on `test_apply.py` which fails on master because of the bug; passes with this PR. One existing test was marked *xfail* but the *xfail* is now removed. One existing test previously had to manipulate the expected index, but that is no longer necessary. \r\n\r\nAll of the copy-pasteable examples from #16646 are fixed with this PR. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35440",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35440/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35440/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35440/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35440",
    "id": 667422468,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU4MDkxNzc3",
    "number": 35440,
    "title": "BUG: CategoricalIndex.format",
    "user": {
      "login": "topper-123",
      "id": 26364415,
      "node_id": "MDQ6VXNlcjI2MzY0NDE1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/26364415?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/topper-123",
      "html_url": "https://github.com/topper-123",
      "followers_url": "https://api.github.com/users/topper-123/followers",
      "following_url": "https://api.github.com/users/topper-123/following{/other_user}",
      "gists_url": "https://api.github.com/users/topper-123/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/topper-123/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/topper-123/subscriptions",
      "organizations_url": "https://api.github.com/users/topper-123/orgs",
      "repos_url": "https://api.github.com/users/topper-123/repos",
      "events_url": "https://api.github.com/users/topper-123/events{/privacy}",
      "received_events_url": "https://api.github.com/users/topper-123/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-28T22:28:20Z",
    "updated_at": "2020-07-29T08:09:27Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35440",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35440",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35440.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35440.patch"
    },
    "body": "- [x] closes #35439\r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [x] whatsnew entry\r\n\r\nI've temporarily put the whatsnewentry in the v.1.1.0 release note, because there isn't a v.1.1.1 version yet. I'll move it, before this is merged.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35439",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35439/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35439/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35439/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35439",
    "id": 667401325,
    "node_id": "MDU6SXNzdWU2Njc0MDEzMjU=",
    "number": 35439,
    "title": "BUG: output of df.to_string depends on whether columns is a CategoricalIndex or not",
    "user": {
      "login": "topper-123",
      "id": 26364415,
      "node_id": "MDQ6VXNlcjI2MzY0NDE1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/26364415?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/topper-123",
      "html_url": "https://github.com/topper-123",
      "followers_url": "https://api.github.com/users/topper-123/followers",
      "following_url": "https://api.github.com/users/topper-123/following{/other_user}",
      "gists_url": "https://api.github.com/users/topper-123/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/topper-123/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/topper-123/subscriptions",
      "organizations_url": "https://api.github.com/users/topper-123/orgs",
      "repos_url": "https://api.github.com/users/topper-123/repos",
      "events_url": "https://api.github.com/users/topper-123/events{/privacy}",
      "received_events_url": "https://api.github.com/users/topper-123/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1218227310,
        "node_id": "MDU6TGFiZWwxMjE4MjI3MzEw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Index",
        "name": "Index",
        "color": "e99695",
        "default": false,
        "description": "Related to the Index class or subclasses"
      },
      {
        "id": 13101118,
        "node_id": "MDU6TGFiZWwxMzEwMTExOA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting",
        "name": "Output-Formatting",
        "color": "ededed",
        "default": false,
        "description": "__repr__ of pandas objects, to_string"
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/75",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels",
      "id": 5640672,
      "node_id": "MDk6TWlsZXN0b25lNTY0MDY3Mg==",
      "number": 75,
      "title": "1.1.1",
      "description": "on-merge: backport to 1.1.x",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 14,
      "closed_issues": 4,
      "state": "open",
      "created_at": "2020-07-10T13:54:44Z",
      "updated_at": "2020-07-29T15:59:29Z",
      "due_on": "2020-08-15T07:00:00Z",
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2020-07-28T21:44:34Z",
    "updated_at": "2020-07-29T13:40:20Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "The output of ``df.to_string`` is different if the columns is a ``CategoricalIndex`` rather than a normal ``Index``:\r\n\r\n```python\r\n>>> data = [[4, 2], [3, 2], [4, 3]]\r\n>>> cols = [\"aaaaaaaaa\", \"b\"]\r\n>>>  pd.DataFrame(data, columns=cols)\r\n   aaaaaaaaa  b\r\n0          4  2\r\n1          3  2\r\n2          4  3\r\n>>> pd.DataFrame(data, columns=pd.CategoricalIndex(cols))\r\n   aaaaaaaaa  b\r\n0          4          2\r\n1          3          2\r\n2          4          3\r\n```\r\n\r\nWe can see that the width of the \"b\" column depends on the width of the \"a\" column, if the columns are a ``CategoricalIndex``.\r\n\r\nThese two examples should return the same repr.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35438",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35438/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35438/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35438/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35438",
    "id": 667330187,
    "node_id": "MDU6SXNzdWU2NjczMzAxODc=",
    "number": 35438,
    "title": "DOC: Can't find mention of DataFrame accepting namedtuples as input",
    "user": {
      "login": "sjvrijn",
      "id": 8833517,
      "node_id": "MDQ6VXNlcjg4MzM1MTc=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/8833517?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sjvrijn",
      "html_url": "https://github.com/sjvrijn",
      "followers_url": "https://api.github.com/users/sjvrijn/followers",
      "following_url": "https://api.github.com/users/sjvrijn/following{/other_user}",
      "gists_url": "https://api.github.com/users/sjvrijn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sjvrijn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sjvrijn/subscriptions",
      "organizations_url": "https://api.github.com/users/sjvrijn/orgs",
      "repos_url": "https://api.github.com/users/sjvrijn/repos",
      "events_url": "https://api.github.com/users/sjvrijn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sjvrijn/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/32",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/32",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels",
      "id": 933188,
      "node_id": "MDk6TWlsZXN0b25lOTMzMTg4",
      "number": 32,
      "title": "Contributions Welcome",
      "description": "Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1191,
      "closed_issues": 598,
      "state": "open",
      "created_at": "2015-01-13T10:53:19Z",
      "updated_at": "2020-07-29T01:54:59Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2020-07-28T19:54:08Z",
    "updated_at": "2020-07-29T01:54:59Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "#### Location of the documentation\r\n\r\nUser guide ['Intro to data structures'](https://pandas.pydata.org/docs/dev/user_guide/dsintro.html#dataframe)\r\n(alternatively [`DataFrame` API docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.html?highlight=dataframe#pandas.DataFrame))\r\n\r\n#### Documentation problem\r\n\r\nI recently only found out through a [StackOverflow answer](https://stackoverflow.com/a/51173794/) that the `DataFrame` constructor can take a list of namedtuples and automatically infers column names from it. Until then I had only found the [`DataFrame.from_records`](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.from_records.html#pandas.DataFrame.from_records) constructor, which manually requires specifying `columns=Namedtuple._fields`.\r\n\r\nAfter searching the documentation for [namedtuple](https://pandas.pydata.org/docs/dev/search.html?q=namedtuple), I haven't been able to find an explicit mention of constructors accepting namedtuples, while there is apparently explicit code in the constructor to deal with them nicely. Currently it only finds mentions where internal functions return rows as namedtuples.\r\n\r\nIn contrast, searching for e.g. ['dataclass'](https://pandas.pydata.org/docs/dev/search.html?q=dataclass) finds [an explicit paragraph](https://pandas.pydata.org/docs/dev/user_guide/dsintro.html?highlight=dataclass#from-a-list-of-dataclasses) listing the option.\r\n\r\n#### Suggested fix for documentation\r\n\r\nI would propose adding an explicit mention and/or example somewhere that these kinds of inputs are accepted/encouraged, such that they can be easily found when searching for the 'namedtuple' keyword.\r\n\r\nI can write a similar paragraph as for dataclasses in the intro to data structures, if that is indeed the right place for this.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35437",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35437/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35437/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35437/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35437",
    "id": 667139532,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU3ODY0MzAy",
    "number": 35437,
    "title": "BUG: tuple-of-tuples indexing results in NumPy VisibleDeprecationWarning",
    "user": {
      "login": "simonjayhawkins",
      "id": 13159005,
      "node_id": "MDQ6VXNlcjEzMTU5MDA1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13159005?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/simonjayhawkins",
      "html_url": "https://github.com/simonjayhawkins",
      "followers_url": "https://api.github.com/users/simonjayhawkins/followers",
      "following_url": "https://api.github.com/users/simonjayhawkins/following{/other_user}",
      "gists_url": "https://api.github.com/users/simonjayhawkins/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/simonjayhawkins/subscriptions",
      "organizations_url": "https://api.github.com/users/simonjayhawkins/orgs",
      "repos_url": "https://api.github.com/users/simonjayhawkins/repos",
      "events_url": "https://api.github.com/users/simonjayhawkins/events{/privacy}",
      "received_events_url": "https://api.github.com/users/simonjayhawkins/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 76865106,
        "node_id": "MDU6TGFiZWw3Njg2NTEwNg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Compat",
        "name": "Compat",
        "color": "0052cc",
        "default": false,
        "description": "Related to pandas compatibility with other libraries"
      },
      {
        "id": 2822098,
        "node_id": "MDU6TGFiZWwyODIyMDk4",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Indexing",
        "name": "Indexing",
        "color": "0b02e1",
        "default": false,
        "description": "Related to indexing on series/frames, not to indexes themselves"
      },
      {
        "id": 2189479765,
        "node_id": "MDU6TGFiZWwyMTg5NDc5NzY1",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Nested%20Data",
        "name": "Nested Data",
        "color": "f2f989",
        "default": false,
        "description": "Data where the values are collections."
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2020-07-28T14:53:24Z",
    "updated_at": "2020-07-28T19:42:34Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35437",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35437",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35437.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35437.patch"
    },
    "body": "- [ ] closes #35434\r\n- [ ] tests added / passed\r\n- [ ] passes `black pandas`\r\n- [ ] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35436",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35436/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35436/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35436/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35436",
    "id": 667026239,
    "node_id": "MDU6SXNzdWU2NjcwMjYyMzk=",
    "number": 35436,
    "title": "BUG: pd.read_parquet with pyarrow fails when row number is 0 and contains Pandas extensions type",
    "user": {
      "login": "Holi0317",
      "id": 6838982,
      "node_id": "MDQ6VXNlcjY4Mzg5ODI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6838982?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Holi0317",
      "html_url": "https://github.com/Holi0317",
      "followers_url": "https://api.github.com/users/Holi0317/followers",
      "following_url": "https://api.github.com/users/Holi0317/following{/other_user}",
      "gists_url": "https://api.github.com/users/Holi0317/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Holi0317/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Holi0317/subscriptions",
      "organizations_url": "https://api.github.com/users/Holi0317/orgs",
      "repos_url": "https://api.github.com/users/Holi0317/repos",
      "events_url": "https://api.github.com/users/Holi0317/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Holi0317/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2020-07-28T12:16:53Z",
    "updated_at": "2020-07-28T15:33:02Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [x] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\ndf = pd.DataFrame([], columns=[\"s\"]).astype({\"s\": \"string\"})\r\ndf.to_parquet(\"out.parquet\")\r\ndf2 = pd.read_parquet(\"out.parquet\") # <- Exception thrown here\r\n```\r\n\r\n```python-traceback\r\nTraceback (most recent call last):\r\n  File \"<input>\", line 1, in <module>\r\n    df2 = pd.read_parquet(\"out.parquet\")\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parquet.py\", line 312, in read_parquet\r\n    return impl.read(path, columns=columns, **kwargs)\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/io/parquet.py\", line 126, in read\r\n    result = self.api.parquet.read_table(\r\n  File \"pyarrow/array.pxi\", line 715, in pyarrow.lib._PandasConvertible.to_pandas\r\n  File \"pyarrow/table.pxi\", line 1565, in pyarrow.lib.Table._to_pandas\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 779, in table_to_blockmanager\r\n    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 1116, in _table_to_blocks\r\n    return [_reconstruct_block(item, columns, extension_columns)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 1116, in <listcomp>\r\n    return [_reconstruct_block(item, columns, extension_columns)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 738, in _reconstruct_block\r\n    pd_ext_arr = pandas_dtype.__from_arrow__(arr)\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/arrays/string_.py\", line 83, in __from_arrow__\r\n    return StringArray._concat_same_type(results)\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/arrays/numpy_.py\", line 171, in _concat_same_type\r\n    return cls(np.concatenate(to_concat))\r\n  File \"<__array_function__ internals>\", line 5, in concatenate\r\nValueError: need at least one array to concatenate\r\n```\r\n\r\n#### Problem description\r\n\r\nAll of the code is produced with pyarrow. fastparquet is not affected by this bug as it does not support pandas extension type\r\n(See: https://github.com/dask/fastparquet/issues/465).\r\n\r\nThis problem only occurs when the row number is 0 and contains pandas extension type (`Int64`, `string`, etc).\r\nIt does not happen when there is 1 row. Even if the row contains `pd.NA`. For example, following code works:\r\n\r\n```python\r\nimport pandas as pd\r\ndf = pd.DataFrame([{\"s\": pd.NA}], columns=[\"s\"]).astype({\"s\": \"Int64\"})\r\ndf.to_parquet(\"out.parquet\")\r\npd.read_parquet(\"out.parquet\")\r\n```\r\n\r\nThe above code will restore the DataFrame correctly.\r\n\r\nThe problem does not occur when the column type is normal type. For example, following code works when the `dtype` is `int64`\r\n\r\n```python\r\nimport pandas as pd\r\ndf = pd.DataFrame([], columns=[\"s\"]).astype({\"s\": \"int\"})\r\ndf.to_parquet(\"out.parquet\")\r\npd.read_parquet(\"out.parquet\")\r\n```\r\n\r\nWhen using the pyarrow library to read the parse the output parquet, `.read_table` would fail when converting to pandas DataFrame with similar errors from `pd.read_parquet`. This only occurs on stable. Correct result is produced on environment 1 and environment 2 (See bottom for environment descriptions)\r\n\r\n```python\r\nimport pandas as pd\r\nimport pyarrow.parquet as pq\r\ndf = pd.DataFrame([], columns=[\"s\"]).astype({\"s\": \"int\"})\r\ndf.to_parquet(\"out.parquet\")\r\ntable = pq.read_table(\"out.parquet\")\r\ntable.to_pandas() # Exception here on stable. Correct result on env 1 and 2\r\n```\r\n\r\n```python-traceback\r\nTraceback (most recent call last):\r\n  File \"<input>\", line 1, in <module>\r\n    table.to_pandas()\r\n  File \"pyarrow/array.pxi\", line 715, in pyarrow.lib._PandasConvertible.to_pandas\r\n  File \"pyarrow/table.pxi\", line 1565, in pyarrow.lib.Table._to_pandas\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 779, in table_to_blockmanager\r\n    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 1116, in _table_to_blocks\r\n    return [_reconstruct_block(item, columns, extension_columns)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 1116, in <listcomp>\r\n    return [_reconstruct_block(item, columns, extension_columns)\r\n  File \"/usr/local/lib/python3.8/site-packages/pyarrow/pandas_compat.py\", line 738, in _reconstruct_block\r\n    pd_ext_arr = pandas_dtype.__from_arrow__(arr)\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/arrays/integer.py\", line 113, in __from_arrow__\r\n    return IntegerArray._concat_same_type(results)\r\n  File \"/usr/local/lib/python3.8/site-packages/pandas/core/arrays/masked.py\", line 175, in _concat_same_type\r\n    data = np.concatenate([x._data for x in to_concat])\r\n  File \"<__array_function__ internals>\", line 5, in concatenate\r\nValueError: need at least one array to concatenate\r\n```\r\n\r\nHowever, reading the dataframe with `.read_pandas` would succeed with expected result in all environments.\r\n\r\n```python\r\nimport pandas as pd\r\nimport pyarrow.parquet as pq\r\ndf = pd.DataFrame([], columns=[\"s\"]).astype({\"s\": \"int\"})\r\ndf.to_parquet(\"out.parquet\")\r\ntable = pq.read_pandas(\"out.parquet\")\r\ndf2 = table.to_pandas() # No exception here\r\ndf.equals(df2) # Retruns True\r\n```\r\n\r\nThe produced DataFrame is as expected with correct column type. This could be used as a workround for now.\r\n\r\n#### Expected Output\r\n\r\nThe parquet should be read successfuly.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n(The code is run under docker image `python:3.8-slim`)\r\n\r\n##### Stable environment\r\n\r\nAll packages installed from pip directly\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.7.9-arch1-1\r\nmachine          : x86_64\r\nprocessor        :\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.0.5\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 1.0.0\r\npytables         : None\r\npytest           : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>\r\n\r\n##### Environment 1\r\n\r\nPandas and numpy compiled from source. pyarrow from their [nightly channel](https://arrow.apache.org/docs/python/install.html#installing-nightly-packages)\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 6302f7b98ad24adda2d5a98fef3956f04f28039d\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.7.9-arch1-1\r\nVersion          : #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000\r\nmachine          : x86_64\r\nprocessor        :\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.1.0rc0+8.g6302f7b\r\nnumpy            : 1.20.0.dev0+4690248\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0\r\nCython           : 0.29.21\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 1.1.0.dev19\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n</details>\r\n\r\n##### Environment 2\r\n\r\nPandas and numpy installed from pip. pyarrow from their [nightly channel](https://arrow.apache.org/docs/python/install.html#installing-nightly-packages)\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.7.9-arch1-1\r\nmachine          : x86_64\r\nprocessor        :\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.0.5\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 1.1.0.dev19\r\npytables         : None\r\npytest           : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35434",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35434/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35434/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35434/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35434",
    "id": 666919212,
    "node_id": "MDU6SXNzdWU2NjY5MTkyMTI=",
    "number": 35434,
    "title": "BUG: Shift on a group column when column name is a tuple-of-tuples results in NumPy VisibleDeprecationWarning",
    "user": {
      "login": "misantroop",
      "id": 23288150,
      "node_id": "MDQ6VXNlcjIzMjg4MTUw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/23288150?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/misantroop",
      "html_url": "https://github.com/misantroop",
      "followers_url": "https://api.github.com/users/misantroop/followers",
      "following_url": "https://api.github.com/users/misantroop/following{/other_user}",
      "gists_url": "https://api.github.com/users/misantroop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/misantroop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/misantroop/subscriptions",
      "organizations_url": "https://api.github.com/users/misantroop/orgs",
      "repos_url": "https://api.github.com/users/misantroop/repos",
      "events_url": "https://api.github.com/users/misantroop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/misantroop/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 76865106,
        "node_id": "MDU6TGFiZWw3Njg2NTEwNg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Compat",
        "name": "Compat",
        "color": "0052cc",
        "default": false,
        "description": "Related to pandas compatibility with other libraries"
      },
      {
        "id": 42670965,
        "node_id": "MDU6TGFiZWw0MjY3MDk2NQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Error%20Reporting",
        "name": "Error Reporting",
        "color": "ffa0ff",
        "default": false,
        "description": "Incorrect or improved errors from pandas"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/32",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/32",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels",
      "id": 933188,
      "node_id": "MDk6TWlsZXN0b25lOTMzMTg4",
      "number": 32,
      "title": "Contributions Welcome",
      "description": "Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 1191,
      "closed_issues": 598,
      "state": "open",
      "created_at": "2015-01-13T10:53:19Z",
      "updated_at": "2020-07-29T01:54:59Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 5,
    "created_at": "2020-07-28T09:25:40Z",
    "updated_at": "2020-07-28T15:39:59Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [+] I have checked that this issue has not already been reported.\r\n\r\n- [+] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [+] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\nnp.warnings.filterwarnings('error', category=np.VisibleDeprecationWarning) \r\n\r\ntuple_column =      ('A', ('B', 2),)\r\ndf =                pd.DataFrame({tuple_column: [1]}, index=['q'])\r\ngrp =               df.groupby(level=0)\r\ndf[tuple_column] =  grp[[tuple_column]].shift()\r\n```\r\n\r\n#### Problem description\r\n\r\nShifting a group that has a column name as tuple-of-tuples gives VisibleDeprecationWarning.\r\n\r\n>  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 2562, in shift\r\n    return self._get_cythonized_result(\r\n  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 2457, in _get_cythonized_result\r\n    for idx, obj in enumerate(self._iterate_slices()):\r\n  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\groupby\\generic.py\", line 998, in _iterate_slices\r\n    obj = self._selected_obj\r\n  File \"pandas\\_libs\\properties.pyx\", line 33, in pandas._libs.properties.CachedProperty.__get__\r\n  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\groupby\\groupby.py\", line 641, in _selected_obj\r\n    return self.obj[self._selection]\r\n  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\frame.py\", line 2889, in __getitem__\r\n    if com.is_bool_indexer(key):\r\n  File \"C:\\Python\\lib\\site-packages\\pandas\\core\\common.py\", line 142, in is_bool_indexer\r\n    arr = np.asarray(key)\r\n  File \"C:\\Python\\lib\\site-packages\\numpy\\core\\_asarray.py\", line 83, in asarray\r\n    return array(a, dtype, copy=False, order=order)\r\n\r\n> C:\\Python\\lib\\site-packages\\numpy\\core\\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray\r\n\r\n#### Expected Output\r\n\r\nNo VisibleDeprecationWarning triggered.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\ncommit           : 6302f7b98ad24adda2d5a98fef3956f04f28039d\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.18362\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United Kingdom.1252\r\n\r\npandas           : 1.1.0rc0+8.g6302f7b98\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.5.2\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : 4.9.1\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.3.0rc1+439.g7e9530338\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : 0.50.1\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35432",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35432/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35432/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35432/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35432",
    "id": 666804755,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU3NTg1ODE2",
    "number": 35432,
    "title": "CLN/PERF: move RangeIndex._cached_data to RangeIndex._cache",
    "user": {
      "login": "topper-123",
      "id": 26364415,
      "node_id": "MDQ6VXNlcjI2MzY0NDE1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/26364415?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/topper-123",
      "html_url": "https://github.com/topper-123",
      "followers_url": "https://api.github.com/users/topper-123/followers",
      "following_url": "https://api.github.com/users/topper-123/following{/other_user}",
      "gists_url": "https://api.github.com/users/topper-123/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/topper-123/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/topper-123/subscriptions",
      "organizations_url": "https://api.github.com/users/topper-123/orgs",
      "repos_url": "https://api.github.com/users/topper-123/repos",
      "events_url": "https://api.github.com/users/topper-123/events{/privacy}",
      "received_events_url": "https://api.github.com/users/topper-123/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-28T06:27:36Z",
    "updated_at": "2020-07-28T11:46:18Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35432",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35432",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35432.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35432.patch"
    },
    "body": "The ``cached_data`` is not necessary. It was originally added to allow a check to see it the ndarray had been created, but that's also possible to do by a ``\"_data\" in _cache`` check in the new implemention, which IMO would be more idiomatic.\r\n\r\nThe new implementation has the benefit that the ``_data`` will be copied to new instances, saving the need to create a new ndarray for each new copy of the RangeIndex.\r\n\r\n```python\r\n>>> idx = pd.RangeIndex(1_000_000)\r\n>>> idx[[1, 4]]  # this accesses ._data and saves it in cached_data (master) or _cache[\"_data\"](this PR)\r\n>> %timeit idx._shallow_copy()[[1, 4]]\r\n2.55 ms ± 69.3 µs per loop  # master\r\n17.7 µs ± 405 ns per loop  # this PR\r\n```\r\n\r\nxref #26565.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35429",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35429/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35429/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35429/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35429",
    "id": 666589306,
    "node_id": "MDU6SXNzdWU2NjY1ODkzMDY=",
    "number": 35429,
    "title": "BUG: NA does not propagate through mask and where/ raises AssertionError in 1.1.0rc",
    "user": {
      "login": "johnflavin",
      "id": 1417503,
      "node_id": "MDQ6VXNlcjE0MTc1MDM=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1417503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/johnflavin",
      "html_url": "https://github.com/johnflavin",
      "followers_url": "https://api.github.com/users/johnflavin/followers",
      "following_url": "https://api.github.com/users/johnflavin/following{/other_user}",
      "gists_url": "https://api.github.com/users/johnflavin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/johnflavin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/johnflavin/subscriptions",
      "organizations_url": "https://api.github.com/users/johnflavin/orgs",
      "repos_url": "https://api.github.com/users/johnflavin/repos",
      "events_url": "https://api.github.com/users/johnflavin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/johnflavin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 849023693,
        "node_id": "MDU6TGFiZWw4NDkwMjM2OTM=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray",
        "name": "ExtensionArray",
        "color": "6138b5",
        "default": false,
        "description": "Extending pandas with custom dtypes or arrays."
      },
      {
        "id": 1817503692,
        "node_id": "MDU6TGFiZWwxODE3NTAzNjky",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays",
        "name": "NA - MaskedArrays",
        "color": "8cc645",
        "default": false,
        "description": "Related to pd.NA and nullable extension arrays"
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/75",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels",
      "id": 5640672,
      "node_id": "MDk6TWlsZXN0b25lNTY0MDY3Mg==",
      "number": 75,
      "title": "1.1.1",
      "description": "on-merge: backport to 1.1.x",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 14,
      "closed_issues": 4,
      "state": "open",
      "created_at": "2020-07-10T13:54:44Z",
      "updated_at": "2020-07-29T15:59:29Z",
      "due_on": "2020-08-15T07:00:00Z",
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2020-07-27T21:15:03Z",
    "updated_at": "2020-07-28T09:55:56Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\n>>> a = pd.DataFrame([{'col': 'a'}] * 3).convert_dtypes()\r\n>>> a\r\n  col\r\n0   a\r\n1   a\r\n2   a\r\n>>> tfna = pd.Series([True, False, pd.NA]).convert_dtypes()\r\n>>> tfna\r\n0     True\r\n1    False\r\n2     <NA>\r\ndtype: boolean\r\n>>> a.mask(tfna, 'b')\r\n  col\r\n0   b\r\n1   a\r\n2   b\r\n>>> a.where(tfna, 'b')\r\n  col\r\n0   a\r\n1   b\r\n2   b\r\n\r\n```\r\n\r\n#### Problem description\r\n\r\nWhen replacing values with `mask` or `where`, `pd.NA` values in a boolean series used for the `cond` input are always replaced. This means `pd.NA` gets treated as `False` by `where` but as `True` by `mask`.\r\n\r\n#### Expected Output\r\n\r\nI would expect that `pd.NA` values in `cond` would propagate to the output.\r\n\r\n```python\r\n>>> a.mask(tfna, 'b')\r\n    col\r\n0     b\r\n1     a\r\n2  <NA>\r\n>>> a.where(tfna, 'b')\r\n    col\r\n0     a\r\n1     b\r\n2  <NA>\r\n\r\n```\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.3.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 18.7.0\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.0.5\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.1.1\r\nsetuptools       : 49.2.0.post20200712\r\nCython           : None\r\npytest           : 5.4.3\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.2\r\nIPython          : 7.15.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : 3.2.2\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 0.17.1\r\npytables         : None\r\npytest           : 5.4.3\r\npyxlsb           : None\r\ns3fs             : 0.4.2\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35428",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35428/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35428/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35428/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35428",
    "id": 666459305,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU3Mjk5Mzc2",
    "number": 35428,
    "title": "BUG: Inconsistent date parsing of to_datetime",
    "user": {
      "login": "arw2019",
      "id": 48889395,
      "node_id": "MDQ6VXNlcjQ4ODg5Mzk1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/48889395?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/arw2019",
      "html_url": "https://github.com/arw2019",
      "followers_url": "https://api.github.com/users/arw2019/followers",
      "following_url": "https://api.github.com/users/arw2019/following{/other_user}",
      "gists_url": "https://api.github.com/users/arw2019/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/arw2019/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/arw2019/subscriptions",
      "organizations_url": "https://api.github.com/users/arw2019/orgs",
      "repos_url": "https://api.github.com/users/arw2019/repos",
      "events_url": "https://api.github.com/users/arw2019/events{/privacy}",
      "received_events_url": "https://api.github.com/users/arw2019/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2020-07-27T17:25:40Z",
    "updated_at": "2020-07-29T03:06:29Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35428",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35428",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35428.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35428.patch"
    },
    "body": "- [x] closes #12585\r\n- [x] tests added / passed\r\n- [ ] documentation updated \r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [ ] whatsnew entry (pending 1.2)\r\n\r\nThis PR is an attempt to address concerns about datetime parsing. I'll update the docs if people approve this change.\r\n\r\n#### Original problem\r\nFrom #12585:\r\n``` python\r\nIn [3]: pd.to_datetime([\"31/12/2014\", \"10/03/2011\"]) \r\n   ...:                                                                                                               \r\nOut[3]: DatetimeIndex(['2014-12-31', '2011-03-10'], dtype='datetime64[ns]', freq=None)\r\n```\r\nThe issue is that the first item is parsed as `DD\\MM\\YYYY` whereas for the second the format is `MM\\DD\\YYYY`, and there is no message to alert the user of inconsistency in the output.\r\n\r\nThe problem lies with the `dayfirst` argument that selects between `DD\\MM\\YYYY` and `MM\\DD\\YYYY`. In the parser:\r\nhttps://github.com/pandas-dev/pandas/blob/04e9e0afd476b1b8bed930e47bf60ee20fa78f38/pandas/_libs/tslibs/parsing.pyx#L94-L163\r\nwe try  `DD\\MM\\YYYY` or `MM\\DD\\YYYY` first depending on `dayfirst` but if the result is invalid we try the other. \r\n\r\n#### Proposed change\r\nI'd like to raise warnings whenever we parse in contradiction to the directive of `dayfirst`. The OP, where `dayfirst` defaults to `False`, now raises a Warning:\r\n``` python\r\nIn [4]: pd.to_datetime([\"31/12/2014\", \"10/03/2011\"], dayfirst=False) \r\n   ...:                                                                                                               \r\n/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.\r\n  result, tz_parsed = tslib.array_to_datetime(\r\nOut[4]: DatetimeIndex(['2014-12-31', '2011-10-03'], dtype='datetime64[ns]', freq=None)\r\n```\r\nA downside of this change is that sometimes a consistent output produces unnecessary warnings (due to mismatch with the default value of `dayfirst`):\r\n``` python\r\nIn [11]: pd.to_datetime([\"31/12/2014\", \"30/04/2011\", \"31/05/2016\"] )                                                 \r\n/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.\r\n  result, tz_parsed = tslib.array_to_datetime(\r\n/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 30/04/2011 DD/MM format.\r\n  result, tz_parsed = tslib.array_to_datetime(\r\n/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/05/2016 DD/MM format.\r\n  result, tz_parsed = tslib.array_to_datetime(\r\nOut[11]: DatetimeIndex(['2014-12-31', '2011-04-30', '2016-05-31'], dtype='datetime64[ns]', freq=None)\r\n```\r\nbut these can be silenced with `infer_datetime_format`:\r\n``` python\r\nIn [12]: pd.to_datetime([\"31/12/2014\", \"30/04/2011\", \"31/05/2016\"], infer_datetime_format=True )                      \r\nOut[12]: DatetimeIndex(['2014-12-31', '2011-04-30', '2016-05-31'], dtype='datetime64[ns]', freq=None)\r\n```\r\nFor invalid input (if it cannot be parsed according to a single format) we will *always* raise a warning, even with `infer_datetime_format=True`:\r\n``` python\r\nIn [13]: pd.to_datetime([\"31/12/2014\", \"03/31/2011\"], infer_datetime_format=True)                                     \r\n/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.\r\n  result, tz_parsed = tslib.array_to_datetime(\r\nOut[13]: DatetimeIndex(['2014-12-31', '2011-03-31'], dtype='datetime64[ns]', freq=None)\r\n```\r\n\r\n#### Remaining issues\r\nPersonally I can see a case for raising an error with \r\n``` python\r\nIn [13]: pd.to_datetime([\"31/12/2014\", \"03/31/2011\"], infer_datetime_format=True)                                     \r\n```\r\nsince there's no valid way to process that. I also think that \r\n``` python\r\nIn [11]: pd.to_datetime([\"31/12/2014\", \"30/04/2011\", \"31/05/2016\"])                                                 \r\n```\r\nshouldn't be raising warnings, but I feel much less strongly about that. That said, changing this behaviour will require more heavy-handed alterations to the codebase (and maybe performance implications - not sure).\r\n\r\nI think that the warnings I added here will allow users to figure out the origin of these problems when they turn up and that should do away with most of the headaches.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35427",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35427/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35427/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35427/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35427",
    "id": 666199957,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU3MDg0ODYy",
    "number": 35427,
    "title": "MAINT: Fix issue in StataReader due to upstream changes",
    "user": {
      "login": "bashtage",
      "id": 5585221,
      "node_id": "MDQ6VXNlcjU1ODUyMjE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5585221?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bashtage",
      "html_url": "https://github.com/bashtage",
      "followers_url": "https://api.github.com/users/bashtage/followers",
      "following_url": "https://api.github.com/users/bashtage/following{/other_user}",
      "gists_url": "https://api.github.com/users/bashtage/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bashtage/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bashtage/subscriptions",
      "organizations_url": "https://api.github.com/users/bashtage/orgs",
      "repos_url": "https://api.github.com/users/bashtage/repos",
      "events_url": "https://api.github.com/users/bashtage/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bashtage/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 104865385,
        "node_id": "MDU6TGFiZWwxMDQ4NjUzODU=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Stata",
        "name": "IO Stata",
        "color": "5319e7",
        "default": false,
        "description": "Stata: read_stata, to_stata"
      },
      {
        "id": 127681,
        "node_id": "MDU6TGFiZWwxMjc2ODE=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Refactor",
        "name": "Refactor",
        "color": "FCE94F",
        "default": false,
        "description": "Internal refactoring of code"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/73",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/73",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/73/labels",
      "id": 5479819,
      "node_id": "MDk6TWlsZXN0b25lNTQ3OTgxOQ==",
      "number": 73,
      "title": "1.2",
      "description": "",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 21,
      "closed_issues": 9,
      "state": "open",
      "created_at": "2020-05-29T23:47:32Z",
      "updated_at": "2020-07-29T15:55:35Z",
      "due_on": "2020-11-29T08:00:00Z",
      "closed_at": null
    },
    "comments": 5,
    "created_at": "2020-07-27T10:57:26Z",
    "updated_at": "2020-07-29T11:21:58Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35427",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35427",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35427.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35427.patch"
    },
    "body": "Avoid creating an array of dtypes to workaround NumPy future change\r\n\r\ncloses #35426\r\n\r\n- [X] closes #35426\r\n- [ ] tests added / passed\r\n- [X] passes `black pandas`\r\n- [X] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35426",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35426/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35426/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35426/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35426",
    "id": 666183589,
    "node_id": "MDU6SXNzdWU2NjYxODM1ODk=",
    "number": 35426,
    "title": "CI/COMPAT: read_stata failing in numpy dev pipeline",
    "user": {
      "login": "AlexKirko",
      "id": 23253999,
      "node_id": "MDQ6VXNlcjIzMjUzOTk5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/23253999?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/AlexKirko",
      "html_url": "https://github.com/AlexKirko",
      "followers_url": "https://api.github.com/users/AlexKirko/followers",
      "following_url": "https://api.github.com/users/AlexKirko/following{/other_user}",
      "gists_url": "https://api.github.com/users/AlexKirko/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/AlexKirko/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/AlexKirko/subscriptions",
      "organizations_url": "https://api.github.com/users/AlexKirko/orgs",
      "repos_url": "https://api.github.com/users/AlexKirko/repos",
      "events_url": "https://api.github.com/users/AlexKirko/events{/privacy}",
      "received_events_url": "https://api.github.com/users/AlexKirko/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 48070600,
        "node_id": "MDU6TGFiZWw0ODA3MDYwMA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/CI",
        "name": "CI",
        "color": "a2bca7",
        "default": false,
        "description": "Related to Continuous Integration"
      },
      {
        "id": 76865106,
        "node_id": "MDU6TGFiZWw3Njg2NTEwNg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Compat",
        "name": "Compat",
        "color": "0052cc",
        "default": false,
        "description": "Related to pandas compatibility with other libraries"
      },
      {
        "id": 104865385,
        "node_id": "MDU6TGFiZWwxMDQ4NjUzODU=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Stata",
        "name": "IO Stata",
        "color": "5319e7",
        "default": false,
        "description": "Stata: read_stata, to_stata"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/75",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/75/labels",
      "id": 5640672,
      "node_id": "MDk6TWlsZXN0b25lNTY0MDY3Mg==",
      "number": 75,
      "title": "1.1.1",
      "description": "on-merge: backport to 1.1.x",
      "creator": {
        "login": "jreback",
        "id": 953992,
        "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
        "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jreback",
        "html_url": "https://github.com/jreback",
        "followers_url": "https://api.github.com/users/jreback/followers",
        "following_url": "https://api.github.com/users/jreback/following{/other_user}",
        "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
        "organizations_url": "https://api.github.com/users/jreback/orgs",
        "repos_url": "https://api.github.com/users/jreback/repos",
        "events_url": "https://api.github.com/users/jreback/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jreback/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 14,
      "closed_issues": 4,
      "state": "open",
      "created_at": "2020-07-10T13:54:44Z",
      "updated_at": "2020-07-29T15:59:29Z",
      "due_on": "2020-08-15T07:00:00Z",
      "closed_at": null
    },
    "comments": 6,
    "created_at": "2020-07-27T10:34:35Z",
    "updated_at": "2020-07-28T14:47:37Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [X] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n#### Problem description\r\n\r\nLooks like a change in numpy broke our `read_stata` code, so now we have a bunch of `read_stata` test errors popping up during CI in the numpy_dev pipeline. Maybe this [Numpy PR](https://github.com/numpy/numpy/pull/16943) somehow broke things? I don't think any other PR merged during the last 24 hours could have possibly done so, although I might be missing something.\r\n\r\nError example:\r\n```\r\npandas/tests/io/test_stata.py:52: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\npandas/io/stata.py:1928: in read_stata\r\n    data = reader.read()\r\npandas/io/stata.py:1646: in read\r\n    cols_ = np.where(self.dtyplist)[0]\r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n\r\nargs = ([<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float32'>, ...],)\r\nkwargs = {}\r\nrelevant_args = ([<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float32'>, ...], None, None)\r\n\r\n>   ???\r\nE   ValueError: invalid __array_struct__\r\n```\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35425",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35425/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35425/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35425/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35425",
    "id": 666160202,
    "node_id": "MDU6SXNzdWU2NjYxNjAyMDI=",
    "number": 35425,
    "title": "BUG: attrs lost for Series in DataFrame",
    "user": {
      "login": "RobertRosca",
      "id": 32569096,
      "node_id": "MDQ6VXNlcjMyNTY5MDk2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/32569096?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RobertRosca",
      "html_url": "https://github.com/RobertRosca",
      "followers_url": "https://api.github.com/users/RobertRosca/followers",
      "following_url": "https://api.github.com/users/RobertRosca/following{/other_user}",
      "gists_url": "https://api.github.com/users/RobertRosca/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RobertRosca/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RobertRosca/subscriptions",
      "organizations_url": "https://api.github.com/users/RobertRosca/orgs",
      "repos_url": "https://api.github.com/users/RobertRosca/repos",
      "events_url": "https://api.github.com/users/RobertRosca/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RobertRosca/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1539579994,
        "node_id": "MDU6TGFiZWwxNTM5NTc5OTk0",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/metadata",
        "name": "metadata",
        "color": "56efc9",
        "default": false,
        "description": "_metadata attribute"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 4,
    "created_at": "2020-07-27T10:04:47Z",
    "updated_at": "2020-07-29T14:00:57Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n  - Has sort of come up in other issues related to metadata/attrs not propagating through properly, however I haven't seen any issues specifically about `Series` attrs being lost when put into a `DataFrame`.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [x] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\nSee this [GitHub Gist Notebook](https://gist.github.com/RobertRosca/d3c53151dd93242c448daf008fb4bb23).\r\n\r\nSummary of the issue is:\r\n\r\n```python\r\nimport pandas as pd\r\n\r\n#  Make some dummy dataframe\r\ndf = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})\r\n\r\n#  Make some dummy series\r\ncol1_w_attr = df[\"col1\"].copy()\r\n#  Add some attrs to it\r\ncol1_w_attr.attrs[\"test_attr\"] = 1\r\ndf[\"col1_w_attr\"] = col1_w_attr\r\n#  Issue 1: The attrs are missing, call `__finalize__` manually\r\ndf[\"col1_w_attr\"].__finalize__(col1_w_attr)\r\n\r\n#  Repeat the above with another column:\r\ncol2_w_attr = df[\"col2\"].copy()\r\ncol2_w_attr.attrs[\"test_attr\"] = 2\r\ndf[\"col2_w_attr\"] = col2_w_attr\r\ndf[\"col2_w_attr\"].__finalize__(col2_w_attr)\r\n\r\n#  Attrs are present as before\r\ndf[\"col2_w_attr\"].attrs\r\n\r\n#  Issue 2: col1_w_attrs is now missing its attrs:\r\ndf[\"col1_w_attr\"].attrs\r\n```\r\n\r\n#### Problem description\r\n\r\nFirst issue is that attrs are not propagated through when a `Series` is added to a `DataFrame` (likely related to #28283).\r\n\r\nSecond issue is that if you call `__finalize__` to make sure that the attrs are present, once you add another column in or modify the dataframe, the attrs already present for a column are lost. My guess is that when the DataFrame is modified, finalize is not called per-column again, but I haven't looked into it much.\r\n\r\nI'd be happy to help with this issue, however there are already many issues related to this topic and a few branches where others are working on attrs/metadata/finalize, so I'm a bit hesitant to start work as it'll probably conflict with what has already been done.\r\n\r\nWhat would be the best place to discuss collaboration on this?\r\n\r\n#### Expected Output\r\n\r\nExpectation would be that you can attach some attrs to a Series, place it into a dataframe, modify/work with the dataframe, then access the attrs again.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nimport pandas as pd\r\n\r\npd.show_versions()\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.3.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.7.0-3-MANJARO\r\nmachine          : x86_64\r\nprocessor        : \r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.0.5\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 19.2.3\r\nsetuptools       : 41.2.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.2\r\nIPython          : 7.16.1\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nlxml.etree       : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npytest           : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nxlsxwriter       : None\r\nnumba            : None\r\n\r\n</details>\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35424",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35424/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35424/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35424/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/35424",
    "id": 666146406,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDU3MDQwNTg0",
    "number": 35424,
    "title": "TST: adding test for .describe() with duplicate columns",
    "user": {
      "login": "smithto1",
      "id": 3813175,
      "node_id": "MDQ6VXNlcjM4MTMxNzU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3813175?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smithto1",
      "html_url": "https://github.com/smithto1",
      "followers_url": "https://api.github.com/users/smithto1/followers",
      "following_url": "https://api.github.com/users/smithto1/following{/other_user}",
      "gists_url": "https://api.github.com/users/smithto1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smithto1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smithto1/subscriptions",
      "organizations_url": "https://api.github.com/users/smithto1/orgs",
      "repos_url": "https://api.github.com/users/smithto1/repos",
      "events_url": "https://api.github.com/users/smithto1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smithto1/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 697792067,
        "node_id": "MDU6TGFiZWw2OTc3OTIwNjc=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Apply",
        "name": "Apply",
        "color": "fbca04",
        "default": false,
        "description": "Apply, Aggregate, Transform"
      },
      {
        "id": 233160,
        "node_id": "MDU6TGFiZWwyMzMxNjA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Groupby",
        "name": "Groupby",
        "color": "729FCF",
        "default": false,
        "description": null
      },
      {
        "id": 127685,
        "node_id": "MDU6TGFiZWwxMjc2ODU=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Testing",
        "name": "Testing",
        "color": "C4A000",
        "default": false,
        "description": "Custom testing functions or related to the test suite"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-27T09:47:09Z",
    "updated_at": "2020-07-27T17:42:30Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/35424",
      "html_url": "https://github.com/pandas-dev/pandas/pull/35424",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/35424.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/35424.patch"
    },
    "body": "- [x] closes #35423 \r\n- [x] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\r\n\r\nWhile working on #35314 I made a change that broke `GroupBy.apply` if you called it on a DataFrame with duplicate columns; however, this break was not caught by any test. Was just caught on inpsection: https://github.com/pandas-dev/pandas/pull/35314#discussion_r460000612\r\n\r\nThis PR is just to add a test for this case to ensure it works and doesn't break again in the future. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/35423",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35423/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35423/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/35423/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/35423",
    "id": 666144923,
    "node_id": "MDU6SXNzdWU2NjYxNDQ5MjM=",
    "number": 35423,
    "title": "TST: Add test for `GroupBy.describe()` with duplicate columns",
    "user": {
      "login": "smithto1",
      "id": 3813175,
      "node_id": "MDQ6VXNlcjM4MTMxNzU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3813175?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smithto1",
      "html_url": "https://github.com/smithto1",
      "followers_url": "https://api.github.com/users/smithto1/followers",
      "following_url": "https://api.github.com/users/smithto1/following{/other_user}",
      "gists_url": "https://api.github.com/users/smithto1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smithto1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smithto1/subscriptions",
      "organizations_url": "https://api.github.com/users/smithto1/orgs",
      "repos_url": "https://api.github.com/users/smithto1/repos",
      "events_url": "https://api.github.com/users/smithto1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smithto1/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 697792067,
        "node_id": "MDU6TGFiZWw2OTc3OTIwNjc=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Apply",
        "name": "Apply",
        "color": "fbca04",
        "default": false,
        "description": "Apply, Aggregate, Transform"
      },
      {
        "id": 233160,
        "node_id": "MDU6TGFiZWwyMzMxNjA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Groupby",
        "name": "Groupby",
        "color": "729FCF",
        "default": false,
        "description": null
      },
      {
        "id": 127685,
        "node_id": "MDU6TGFiZWwxMjc2ODU=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Testing",
        "name": "Testing",
        "color": "C4A000",
        "default": false,
        "description": "Custom testing functions or related to the test suite"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-07-27T09:44:59Z",
    "updated_at": "2020-07-27T11:27:58Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [x] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\nWhile working on #35314 I made a change that broke `GroupBy.apply` if you called it on a DataFrame with duplicate columns; however, this break as not caught by any test. Was just caught on inpsection: https://github.com/pandas-dev/pandas/pull/35314#discussion_r460000612\r\n\r\nThis issue is just to add a test for this case to ensure it works and doesn't break again in the future. ",
    "performed_via_github_app": null
  }
]